import type { ProductionQualityOverride } from './productionQualityTypes';

/** Generated by scripts/question-audit/buildProductionQualityManifest.ts */
export const PRODUCTION_QUALITY_OVERRIDES: Record<string, ProductionQualityOverride> = {
  "b4m1-k1-q1": {
    "scenarioText": "B-4 sees a kid with tight fists and a frown. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, mood scanner corner (K-1).",
    "choices": [
      "Pause and notice one more detail first",
      "Angry",
      "Ask a short clarifying question",
      "Ready for a snack"
    ],
    "correctIndex": 1
  },
  "b4m1-k1-q2": {
    "scenarioText": "B-4 sees a kid smiling big and bouncing on their toes. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, feeling label station (K-1).",
    "choices": [
      "Happy",
      "Pause and notice one more detail first",
      "Ask a short clarifying question",
      "Compare two possible next steps"
    ],
    "correctIndex": 0
  },
  "b4m1-k1-q3": {
    "scenarioText": "A kid has quiet tears and a droopy face. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, calm-name practice desk (K-1).",
    "choices": [
      "Sad",
      "Pause and notice one more detail first",
      "Ask a short clarifying question",
      "Compare two possible next steps"
    ],
    "correctIndex": 0
  },
  "b4m2-k1-q1": {
    "scenarioText": "If your heart beats fast and your body feels jumpy,. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, body signal panel (K-1).",
    "choices": [
      "Ask for help after trying one breath",
      "Take slow breaths",
      "Do the easiest calm step first",
      "Keep making your body more jumpy"
    ],
    "correctIndex": 1
  },
  "b4m2-k1-q2": {
    "scenarioText": "B-4 sees butterflies in a kid's tummy before show-and-tell. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, heartbeat tracker wall (K-1).",
    "choices": [
      "A nervous tummy clue",
      "A hungry-for-pizza clue",
      "A robot-startup clue",
      "A nothing-is-happening clue"
    ],
    "correctIndex": 0
  },
  "b4m2-k1-q3": {
    "scenarioText": "A kid yawns and their eyes feel heavy. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, shoulder-check station (K-1).",
    "choices": [
      "Tired",
      "Pause and notice one more detail first",
      "Ask a short clarifying question",
      "Compare two possible next steps"
    ],
    "correctIndex": 0
  },
  "b4m3-k1-q1": {
    "scenarioText": "A friend drops their crayons. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, brave choice console (K-1).",
    "choices": [
      "Help pick them up",
      "Laugh and walk away",
      "Wait to help until someone else starts",
      "Pretend the floor did it"
    ],
    "correctIndex": 0
  },
  "b4m3-k1-q2": {
    "scenarioText": "A classmate looks sad and alone at recess. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, helpful-choice practice pad (K-1).",
    "choices": [
      "Ask if they want to play",
      "Watch from far away and hope someone else helps",
      "Pause and notice one more detail first",
      "Pretend you did not see them"
    ],
    "correctIndex": 0
  },
  "b4m3-k1-q3": {
    "scenarioText": "The teacher asks everyone to line up quietly. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, courage button bay (K-1).",
    "choices": [
      "Try your best to follow directions",
      "Keep running in circles",
      "Stay in line and take one small calm breath",
      "Blame the line for being slow"
    ],
    "correctIndex": 0
  },
  "b4m4-k1-q1": {
    "scenarioText": "Your brain feels busy. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, focus reset station (K-1).",
    "choices": [
      "Take one slow breath",
      "Wait and hope focus comes back on its own",
      "Start with the first small part of the task",
      "Rip up the page and stop trying"
    ],
    "correctIndex": 0
  },
  "b4m4-k1-q2": {
    "scenarioText": "Your body feels wiggly and you cannot sit still. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, breathe-move-start panel (K-1).",
    "choices": [
      "Move — a quick stretch or wiggle break",
      "Breathe — hold your breath for ten minutes",
      "Start Small — write the whole report now",
      "Wait and hope focus returns later"
    ],
    "correctIndex": 0
  },
  "b4m4-k1-q3": {
    "scenarioText": "A task feels hard to start. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, attention reset nook (K-1).",
    "choices": [
      "Pick one tiny first step",
      "Do everything at once",
      "Wait until it feels easy",
      "Put the task away and avoid it"
    ],
    "correctIndex": 0
  },
  "b4m5-k1-q1": {
    "scenarioText": "What can B-4 do to calm a big feeling. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, calm-down countdown timer (K-1).",
    "choices": [
      "Count slowly and breathe",
      "Make the feeling race",
      "Say \"go away\" to the feeling",
      "Knock over the chair"
    ],
    "correctIndex": 0
  },
  "b4m5-k1-q2": {
    "scenarioText": "Your body feels wiggly and jumpy. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, big-feeling alert bell (K-1).",
    "choices": [
      "Take slow breaths with B-4",
      "Run in circles faster",
      "Hold your breath until you float",
      "Shake your lunchbox at the wall"
    ],
    "correctIndex": 0
  },
  "b4m5-k1-q3": {
    "scenarioText": "B-4 says \"3… 2… 1… breathe.\". Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, cool-down practice mat (K-1).",
    "choices": [
      "It gives your body time to calm down",
      "It helps feelings settle enough to make a good choice",
      "It gives your thinking brain time to catch up",
      "It helps you handle upset feelings more safely"
    ],
    "correctIndex": 0
  },
  "b4m6-k1-q1": {
    "scenarioText": "You knocked over someone's blocks. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, oops repair lab bench (K-1).",
    "choices": [
      "Say sorry and help rebuild",
      "Wait and hope someone else fixes it",
      "Say the blocks jumped",
      "Laugh at the mess"
    ],
    "correctIndex": 0
  },
  "b4m6-k1-q2": {
    "scenarioText": "You spilled juice on a friend's paper. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, mistake-fix worktable (K-1).",
    "choices": [
      "Say sorry and help clean up",
      "Say nothing and hope nobody notices",
      "Say the juice was thirsty",
      "Walk away really fast"
    ],
    "correctIndex": 0
  },
  "b4m6-k1-q3": {
    "scenarioText": "What is repair. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, repair toolkit shelf (K-1).",
    "choices": [
      "Fixing what your mistake hurt",
      "Waiting for the mistake to be forgotten",
      "Blaming someone else",
      "Running until everyone forgets"
    ],
    "correctIndex": 0
  },
  "b4m7-k1-q1": {
    "scenarioText": "A puzzle is hard. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, confidence charger dock (K-1).",
    "choices": [
      "I can try one more piece",
      "I am bad at everything",
      "This puzzle is my enemy",
      "I can take a short break, then try once more"
    ],
    "correctIndex": 0
  },
  "b4m7-k1-q2": {
    "scenarioText": "Your block tower fell down. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, effort-notice station (K-1).",
    "choices": [
      "Try again, one block at a time",
      "This tower is hard today, but I can improve",
      "The blocks are being mean",
      "I quit building things"
    ],
    "correctIndex": 0
  },
  "b4m7-k1-q3": {
    "scenarioText": "What charges the Confidence Charger. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, try-again boost panel (K-1).",
    "choices": [
      "Trying again even when it is hard",
      "Learning from mistakes and trying again",
      "Only doing easy things",
      "Waiting until someone else does it"
    ],
    "correctIndex": 0
  },
  "b4m8-k1-q1": {
    "scenarioText": "You feel mad. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, focus flame altar (K-1).",
    "choices": [
      "Name the feeling and take a breath",
      "Do the easiest calm step first",
      "Pretend feelings are not real",
      "Pause and notice one more detail first"
    ],
    "correctIndex": 0
  },
  "b4m8-k1-q2": {
    "scenarioText": "You feel sad. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, final mission review desk (K-1).",
    "choices": [
      "Wait and hope sadness goes away by itself",
      "Tell a grown-up or take a breath",
      "Do one small calming step, then ask for help",
      "Throw things so people notice you are sad"
    ],
    "correctIndex": 1
  },
  "b4m8-k1-q3": {
    "scenarioText": "What does B-4's Focus Flame need. Scene: At Focus Flame Academy's youngest wing, B-4's dashboard glows beside the calm corner, courage combo checklist (K-1).",
    "choices": [
      "Feelings and helper moves working together",
      "Only being happy all the time",
      "Having feelings and using helper moves",
      "Ignoring every body signal"
    ],
    "correctIndex": 0
  },
  "cm1-68-q1": {
    "scenarioText": "What makes Charlie's conclusion stronger. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, garden footprint trail (6-8).",
    "choices": [
      "Multiple pieces of matching evidence",
      "The funniest theory",
      "The first idea he has",
      "A guess from across the playground"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-68-q2": {
    "scenarioText": "Charlie finds footprints, nibbled lettuce, and a trail of seeds. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, lettuce mystery bed (6-8).",
    "choices": [
      "All three clues point to the same kind of visitor",
      "Three clues means three separate mysteries",
      "Seeds mean someone planted a garden inside the garden",
      "Lettuce crumbs prove the hamster is guilty"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-68-q1": {
    "scenarioText": "What variable did Charlie change. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, floating orange tub (6-8).",
    "choices": [
      "Whether the orange had a peel",
      "How much water was in the bowl",
      "The temperature of the water",
      "Whether both oranges were the same size"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-68-q2": {
    "scenarioText": "Which hypothesis best fits Charlie's results. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, peel-and-drop station (6-8).",
    "choices": [
      "The orange floated because Charlie watched carefully",
      "Peeling changes how water and air interact with the orange",
      "The peel helps trap air, which affects whether the orange floats",
      "The result cannot be explained with evidence"
    ],
    "correctIndex": 2,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-68-q3": {
    "scenarioText": "Charlie wants to test his hypothesis again. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, sink-or-float table (6-8).",
    "choices": [
      "The same bowl, water level, and orange size",
      "A different fruit, bowl, and room each time",
      "Only the hypothesis — change everything else",
      "Use the same setup so the result is comparable"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-68-q1": {
    "scenarioText": "What is the best evidence-based next step. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, squeak hunt shelf (6-8).",
    "choices": [
      "Test whether the sound stops when",
      "Test the likely source before concluding",
      "Pause and notice one more detail first",
      "Ask everyone to talk louder"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-68-q2": {
    "scenarioText": "Charlie turns off the fan and the squeak stops. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, club interruption corner (6-8).",
    "choices": [
      "The fan was likely connected to the sound",
      "The cabinet ghost took a break",
      "The fan setup likely needs adjustment or maintenance",
      "Patterns are not useful"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-68-q3": {
    "scenarioText": "Why is \"notice. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, mystery sound map (6-8).",
    "choices": [
      "Timing helps link the sound to a specific cause",
      "Timing makes the sound scarier",
      "Pause and notice one more detail first",
      "Timing only matters for music class"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-68-q1": {
    "scenarioText": "Charlie wants a stronger eruption. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, baking soda volcano bay (6-8).",
    "choices": [
      "All variables except the one",
      "Pause and notice one more detail first",
      "Only the volcano name",
      "The funniest guess"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-68-q2": {
    "scenarioText": "Charlie tests more vinegar while keeping baking soda and cup size the same. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, tiny-eruption table (6-8).",
    "choices": [
      "Testing one independent variable wh",
      "Changing every variable at once",
      "Avoiding measurement on purpose",
      "Pause and notice one more detail first"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-68-q1": {
    "scenarioText": "What is the best investigation plan. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, twin plant window ledge (6-8).",
    "choices": [
      "Compare environmental conditions and change on",
      "Keep one plant as a comparison while testing one change",
      "Collect data before deciding the cause",
      "Stop observing after one day"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-68-q2": {
    "scenarioText": "Charlie records light hours, water amount, and soil moisture for both plants. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, thriving-vs-wilt shelf (6-8).",
    "choices": [
      "To compare conditions and spot wh",
      "To write a plant report card",
      "To prove plants have opinions",
      "To avoid testing anything"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-68-q1": {
    "scenarioText": "What is the strongest debugging process. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, mini robot test lane (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-68-q2": {
    "scenarioText": "Charlie's robot spins left. He checks: power, wheel connection, motor wire, and code. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, spin-fix workbench (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm7-68-q1": {
    "scenarioText": "What is the best design strategy. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, marshmallow tower mat (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm7-68-q2": {
    "scenarioText": "Charlie's team documents each version: height, wobble, and. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, leaning-build table (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm8-68-q1": {
    "scenarioText": "Which claim is strongest. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, science fair booth row (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-23-q1": {
    "scenarioText": "Zeke wants to join the game. Scene: During recess team time, Zeke listens while the group figures out next steps, new-table lunch spot (2-3).",
    "choices": [
      "Ask politely and wait for an answer",
      "Grab the cards",
      "Tell everyone he is the boss",
      "Walk away without trying"
    ],
    "correctIndex": 0
  },
  "zkm1-23-q2": {
    "scenarioText": "The group looks busy. Scene: During recess team time, Zeke listens while the group figures out next steps, open-seat card game (2-3).",
    "choices": [
      "Can I join the next round?",
      "You have to let me play now",
      "Your game looks stupid",
      "Say nothing and stare until someone notices"
    ],
    "correctIndex": 0
  },
  "zkm2-23-q2": {
    "scenarioText": "Zeke is running fast but hears Maya call his name. Scene: During recess team time, Zeke listens while the group figures out next steps, team game sideline (2-3).",
    "choices": [
      "Maya is open and ready for a pass",
      "The crowd wants him to stop running",
      "Maya wants to take the ball home",
      "Running can still include smart passing choices"
    ],
    "correctIndex": 0
  },
  "zkm3-23-q1": {
    "scenarioText": "What should Zeke suggest. Scene: During recess team time, Zeke listens while the group figures out next steps, poster project table (2-3).",
    "choices": [
      "Let's pick jobs for each person",
      "I will do everything myself",
      "Nobody gets to help",
      "Let's argue about the glue"
    ],
    "correctIndex": 0
  },
  "zkm4-23-q1": {
    "scenarioText": "What is a brave way to help. Scene: During recess team time, Zeke listens while the group figures out next steps, hurt-joke hallway (2-3)."
  },
  "zkm4-23-q3": {
    "scenarioText": "The student. Scene: During recess team time, Zeke listens while the group figures out next steps, friendship repair step (2-3).",
    "choices": [
      "Go with them or invite them back respectfully",
      "Stay with the group that laughed",
      "Text everyone about what happened",
      "Pretend he did not notice them leave"
    ],
    "correctIndex": 0
  },
  "zkm5-23-q1": {
    "scenarioText": "What makes Zeke's apology better. Scene: During recess team time, Zeke listens while the group figures out next steps, saved-seat promise spot (2-3)."
  },
  "zkm5-23-q2": {
    "scenarioText": "Zeke says sorry but keeps playing his game. Scene: During recess team time, Zeke listens while the group figures out next steps, quiet-upset bench (2-3)."
  },
  "zkm6-23-q1": {
    "scenarioText": "What helps Zeke feel more ready. Scene: During recess team time, Zeke listens while the group figures out next steps, talent signup sheet (2-3)."
  },
  "zkm6-23-q2": {
    "scenarioText": "Zeke feels nervous before the talent show. Scene: During recess team time, Zeke listens while the group figures out next steps, flippy-stomach stage door (2-3)."
  },
  "zkm6-23-q3": {
    "scenarioText": "What does practice do for courage. Scene: During recess team time, Zeke listens while the group figures out next steps, tryout courage corner (2-3)."
  },
  "zkm7-23-q1": {
    "scenarioText": "What should Zeke say. Scene: During recess team time, Zeke listens while the group figures out next steps, captain clipboard huddle (2-3).",
    "choices": [
      "Come join us. We need anothe",
      "You probably cannot play",
      "Pause and notice one more detail first",
      "Only my friends can join"
    ],
    "correctIndex": 0
  },
  "zkm7-23-q2": {
    "scenarioText": "The kid picked last looks nervous. Scene: During recess team time, Zeke listens while the group figures out next steps, pick-last roster board (2-3)."
  },
  "zkm7-23-q3": {
    "scenarioText": "What is part of a captain's job. Scene: During recess team time, Zeke listens while the group figures out next steps, team leader mat (2-3).",
    "choices": [
      "Help everyone feel they can contribute",
      "Win by leaving people out",
      "Rotate turns so different teammates contribute",
      "Let one person do everything"
    ],
    "correctIndex": 0
  },
  "zkm8-23-q1": {
    "scenarioText": "What should Zeke ask in the huddle. Scene: During recess team time, Zeke listens while the group figures out next steps, final huddle circle (2-3).",
    "choices": [
      "What went well, and what can we improve?",
      "Who should we blame?",
      "Who was the worst?",
      "What is one thing we should try differently next time?"
    ],
    "correctIndex": 0
  },
  "zkm8-23-q2": {
    "scenarioText": "The team lost but tried hard. Scene: During recess team time, Zeke listens while the group figures out next steps, proud-and-frustrated line (2-3).",
    "choices": [
      "What went well, and what can we improve?",
      "Who messed up the most?",
      "Who should we blame?",
      "How can we include everyone better next round?"
    ],
    "correctIndex": 0
  },
  "cm8-k1-q1": {
    "scenarioText": "Which project should Charlie trust more. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, science fair booth row (K-1)."
  },
  "cm8-k1-q2": {
    "scenarioText": "One student measured plant height every day. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, opposite-results display (K-1)."
  },
  "cm8-k1-q3": {
    "scenarioText": "A project says \"music wins\" but nobody wrote anything down. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, evidence compare desk (K-1)."
  },
  "cm8-23-q1": {
    "scenarioText": "What makes a science fair test fair. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, science fair booth row (2-3)."
  },
  "cm8-23-q2": {
    "scenarioText": "Project A gave both plants the same water and light. Project B did not. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, opposite-results display (2-3)."
  },
  "cm8-23-q3": {
    "scenarioText": "One project tested three plants with music and three in silence. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, evidence compare desk (2-3)."
  },
  "cm8-45-q1": {
    "scenarioText": "What should Charlie compare. Scene: At the invention table, Charlie Perk compares two test results side by side, science fair booth row (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm8-45-q2": {
    "scenarioText": "The music project kept a chart of heights. The silence project only has a drawing. Scene: At the invention table, Charlie Perk compares two test results side by side, opposite-results display (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm8-45-q3": {
    "scenarioText": "Both projects ran two weeks. One changed water amounts halfway through. Scene: At the invention table, Charlie Perk compares two test results side by side, evidence compare desk (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm8-68-q2": {
    "scenarioText": "The music project tested 6 plants with controlled light, water, and soil. The silence project used 1 plant near a window. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, opposite-results display (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm8-68-q3": {
    "scenarioText": "A judge says, \"I love music, so the music project wins.\". Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, evidence compare desk (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-k1-q1": {
    "scenarioText": "What should Zeke do if his teammate is open. Scene: In the cafeteria, Zeke pauses near a table with an open seat, pass-the-ball circle (K-1)."
  },
  "zkm2-k1-q2": {
    "scenarioText": "It is Zeke's turn to dribble. Scene: In the cafeteria, Zeke pauses near a table with an open seat, team game sideline (K-1)."
  },
  "zkm2-k1-q3": {
    "scenarioText": "Maya asks for the ball. Scene: In the cafeteria, Zeke pauses near a table with an open seat, open-player lane (K-1)."
  },
  "zkm2-23-q1": {
    "scenarioText": "Why is passing a strong choice. Scene: During recess team time, Zeke listens while the group figures out next steps, pass-the-ball circle (2-3)."
  },
  "zkm2-23-q3": {
    "scenarioText": "After Zeke passes and Maya scores,. Scene: During recess team time, Zeke listens while the group figures out next steps, open-player lane (2-3)."
  },
  "zkm2-45-q1": {
    "scenarioText": "Zeke wants to be the hero, but Maya has a better shot. Scene: At the group project table, Zeke balances his idea with the team's plan, pass-the-ball circle (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-45-q2": {
    "scenarioText": "Zeke has a decent shot but two teammates are in better spots. Scene: At the group project table, Zeke balances his idea with the team's plan, team game sideline (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-45-q3": {
    "scenarioText": "The team loses even after a good pass. Scene: At the group project table, Zeke balances his idea with the team's plan, open-player lane (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-68-q1": {
    "scenarioText": "What makes Zeke's pass a strong leadership move. Scene: Before a team captain huddle, Zeke reads the room and the roster, pass-the-ball circle (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-68-q2": {
    "scenarioText": "The defense double-teams Zeke. Scene: Before a team captain huddle, Zeke reads the room and the roster, team game sideline (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm2-68-q3": {
    "scenarioText": "A teammate misses after Zeke's pass. Scene: Before a team captain huddle, Zeke reads the room and the roster, open-player lane (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-k1-q1": {
    "scenarioText": "What helps the group work together. Scene: In the cafeteria, Zeke pauses near a table with an open seat, poster project table (K-1)."
  },
  "zkm3-k1-q2": {
    "scenarioText": "Two kids want to color at the same time. Scene: In the cafeteria, Zeke pauses near a table with an open seat, group-plan clipboard (K-1)."
  },
  "zkm3-k1-q3": {
    "scenarioText": "Someone keeps talking over others. Scene: In the cafeteria, Zeke pauses near a table with an open seat, everyone-talks-at-once desk (K-1)."
  },
  "zkm3-23-q2": {
    "scenarioText": "Three kids want to draw. Scene: During recess team time, Zeke listens while the group figures out next steps, group-plan clipboard (2-3)."
  },
  "zkm3-23-q3": {
    "scenarioText": "Someone is not sure. Scene: During recess team time, Zeke listens while the group figures out next steps, everyone-talks-at-once desk (2-3)."
  },
  "zkm3-45-q1": {
    "scenarioText": "The group is stuck because everyone wants the same task. Scene: At the group project table, Zeke balances his idea with the team's plan, poster project table (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-45-q2": {
    "scenarioText": "The poster needs a title, drawings, and facts. Scene: At the group project table, Zeke balances his idea with the team's plan, group-plan clipboard (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-45-q3": {
    "scenarioText": "One teammate finishes early and has nothing to do. Scene: At the group project table, Zeke balances his idea with the team's plan, everyone-talks-at-once desk (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-68-q1": {
    "scenarioText": "How can Zeke help without taking over. Scene: Before a team captain huddle, Zeke reads the room and the roster, poster project table (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-68-q2": {
    "scenarioText": "Two teammates disagree about the layout. Scene: Before a team captain huddle, Zeke reads the room and the roster, group-plan clipboard (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm3-68-q3": {
    "scenarioText": "The group falls behind because nobody tracked deadlines. Scene: Before a team captain huddle, Zeke reads the room and the roster, everyone-talks-at-once desk (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-k1-q1": {
    "scenarioText": "What should Zeke say first. Scene: In the cafeteria, Zeke pauses near a table with an open seat, new-table lunch spot (K-1)."
  },
  "zkm1-k1-q2": {
    "scenarioText": "The kids say yes. Scene: In the cafeteria, Zeke pauses near a table with an open seat, open-seat card game (K-1).",
    "choices": [
      "Sit down and listen to how the game works",
      "Grab the cards and change the rules",
      "Pause and notice one more detail first",
      "Walk away because they said yes too slowly"
    ],
    "correctIndex": 0
  },
  "zkm1-k1-q3": {
    "scenarioText": "One kid looks shy at the table. Scene: In the cafeteria, Zeke pauses near a table with an open seat, welcome-wave corner (K-1)."
  },
  "zkm1-23-q3": {
    "scenarioText": "Someone says \"maybe later.\". Scene: During recess team time, Zeke listens while the group figures out next steps, welcome-wave corner (2-3)."
  },
  "zkm1-45-q1": {
    "scenarioText": "The group is in the middle of a round. Scene: At the group project table, Zeke balances his idea with the team's plan, new-table lunch spot (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-45-q2": {
    "scenarioText": "Zeke notices everyone is focused on the game. Scene: At the group project table, Zeke balances his idea with the team's plan, open-seat card game (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-45-q3": {
    "scenarioText": "The group welcomes Zeke but one kid does not smile. Scene: At the group project table, Zeke balances his idea with the team's plan, welcome-wave corner (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-68-q1": {
    "scenarioText": "What shows strong social confidence. Scene: Before a team captain huddle, Zeke reads the room and the roster, new-table lunch spot (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-68-q2": {
    "scenarioText": "Zeke gets a polite \"we're full for this round.\". Scene: Before a team captain huddle, Zeke reads the room and the roster, open-seat card game (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm1-68-q3": {
    "scenarioText": "Zeke sees another student hovering near the table too. Scene: Before a team captain huddle, Zeke reads the room and the roster, welcome-wave corner (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-k1-q1": {
    "scenarioText": "What can Zeke say. Scene: In the cafeteria, Zeke pauses near a table with an open seat, hurt-joke hallway (K-1)."
  },
  "zkm4-k1-q2": {
    "scenarioText": "The hurt student looks sad. Scene: In the cafeteria, Zeke pauses near a table with an open seat, laugh-that-stings moment (K-1)."
  },
  "zkm4-k1-q3": {
    "scenarioText": "Zeke wants to help stop the joke. Scene: In the cafeteria, Zeke pauses near a table with an open seat, friendship repair step (K-1)."
  },
  "zkm4-23-q2": {
    "scenarioText": "Some kids keep giggling. Scene: During recess team time, Zeke listens while the group figures out next steps, laugh-that-stings moment (2-3)."
  },
  "zkm4-45-q1": {
    "scenarioText": "What should Zeke do if he wants to redirect the group. Scene: At the group project table, Zeke balances his idea with the team's plan, hurt-joke hallway (4-5).",
    "choices": [
      "Calmly say the joke is not okay and cha",
      "Embarrass the person who made the joke",
      "Pause and notice one more detail first",
      "Pause and notice one more detail first"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-45-q2": {
    "scenarioText": "The joke-maker says \"It was just funny.\". Scene: At the group project table, Zeke balances his idea with the team's plan, laugh-that-stings moment (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-45-q3": {
    "scenarioText": "Zeke wants to support the student. Scene: At the group project table, Zeke balances his idea with the team's plan, friendship repair step (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-68-q1": {
    "scenarioText": "What response shows courage and social skill. Scene: Before a team captain huddle, Zeke reads the room and the roster, hurt-joke hallway (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-68-q2": {
    "scenarioText": "The group gets tense after Zeke speaks up. Scene: Before a team captain huddle, Zeke reads the room and the roster, laugh-that-stings moment (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm4-68-q3": {
    "scenarioText": "Later, Zeke talks to the student. Scene: Before a team captain huddle, Zeke reads the room and the roster, friendship repair step (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-k1-q1": {
    "scenarioText": "What should Zeke do first. Scene: In the cafeteria, Zeke pauses near a table with an open seat, saved-seat promise spot (K-1)."
  },
  "zkm5-k1-q2": {
    "scenarioText": "Zeke's friend is still quiet. Scene: In the cafeteria, Zeke pauses near a table with an open seat, quiet-upset bench (K-1)."
  },
  "zkm5-k1-q3": {
    "scenarioText": "What is repair. Scene: In the cafeteria, Zeke pauses near a table with an open seat, friendship fix table (K-1)."
  },
  "zkm5-23-q3": {
    "scenarioText": "Your friend says they felt left out. Scene: During recess team time, Zeke listens while the group figures out next steps, friendship fix table (2-3).",
    "choices": [
      "Listen and ask what would help",
      "Tell them to cheer up",
      "Change the subject",
      "Pause and notice one more detail first"
    ],
    "correctIndex": 0
  },
  "zkm5-45-q1": {
    "scenarioText": "What should Zeke say. Scene: At the group project table, Zeke balances his idea with the team's plan, saved-seat promise spot (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-45-q2": {
    "scenarioText": "A friend is upset because Zeke broke a promise. Scene: At the group project table, Zeke balances his idea with the team's plan, quiet-upset bench (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-45-q3": {
    "scenarioText": "Which apology is too vague. Scene: At the group project table, Zeke balances his idea with the team's plan, friendship fix table (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-68-q1": {
    "scenarioText": "How can Zeke rebuild trust. Scene: Before a team captain huddle, Zeke reads the room and the roster, saved-seat promise spot (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-68-q2": {
    "scenarioText": "Zeke apologized but made the same mistake again. Scene: Before a team captain huddle, Zeke reads the room and the roster, quiet-upset bench (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm5-68-q3": {
    "scenarioText": "What shows repair is working. Scene: Before a team captain huddle, Zeke reads the room and the roster, friendship fix table (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-k1-q1": {
    "scenarioText": "What can each teammate share. Scene: In the cafeteria, Zeke pauses near a table with an open seat, final huddle circle (K-1)."
  },
  "zkm8-k1-q2": {
    "scenarioText": "Zeke asks. Scene: In the cafeteria, Zeke pauses near a table with an open seat, proud-and-frustrated line (K-1)."
  },
  "zkm8-k1-q3": {
    "scenarioText": "What does a huddle help the team do. Scene: In the cafeteria, Zeke pauses near a table with an open seat, last challenge recap (K-1)."
  },
  "zkm8-23-q3": {
    "scenarioText": "One teammate says they felt left out. Scene: During recess team time, Zeke listens while the group figures out next steps, last challenge recap (2-3)."
  },
  "zkm8-45-q1": {
    "scenarioText": "One teammate says they felt ignored. Scene: At the group project table, Zeke balances his idea with the team's plan, final huddle circle (4-5).",
    "choices": [
      "Listen and plan how to inclu",
      "Tell them they are wrong",
      "Change the subject",
      "Say winning matters more"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-45-q2": {
    "scenarioText": "Some teammates are proud, some frustrated. Scene: At the group project table, Zeke balances his idea with the team's plan, proud-and-frustrated line (4-5).",
    "choices": [
      "Let everyone share and listen",
      "Only let the captain talk",
      "Pretend it was perfect",
      "Blame the frustrated ones"
    ],
    "correctIndex": 0,
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-45-q3": {
    "scenarioText": "What is team reflection. Scene: At the group project table, Zeke balances his idea with the team's plan, last challenge recap (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-68-q1": {
    "scenarioText": "What makes a team reflection useful. Scene: Before a team captain huddle, Zeke reads the room and the roster, final huddle circle (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-68-q2": {
    "scenarioText": "A teammate shares they felt ignored during the challenge. Best team response. Scene: Before a team captain huddle, Zeke reads the room and the roster, proud-and-frustrated line (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm8-68-q3": {
    "scenarioText": "What turns reflection into growth. Scene: Before a team captain huddle, Zeke reads the room and the roster, last challenge recap (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m1-45-q1": {
    "scenarioText": "A student feels excited about presenting but also nervous. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, mood scanner corner (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m1-45-q2": {
    "scenarioText": "A student wins a prize but notices a friend looks upset. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, feeling label station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m1-45-q3": {
    "scenarioText": "A student is proud of their project but embarrassed to share it. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, calm-name practice desk (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-45-q1": {
    "scenarioText": "A student feels hot, tense, and ready to argue. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, body signal panel (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-45-q2": {
    "scenarioText": "A student cannot sit still — legs bouncing, fingers tapping. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, heartbeat tracker wall (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-45-q3": {
    "scenarioText": "A student's brain feels buzzy and they cannot think straight. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, shoulder-check station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m3-45-q1": {
    "scenarioText": "A student is afraid to try because they might be wrong. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, brave choice console (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m3-45-q3": {
    "scenarioText": "A student feels nervous about performing in front of the class. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, courage button bay (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-45-q2": {
    "scenarioText": "A student's mind keeps wandering while reading. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, breathe-move-start panel (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-23-q1": {
    "scenarioText": "A student says something unkind. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, oops repair lab bench (2-3)."
  },
  "b4m6-23-q2": {
    "scenarioText": "You accidentally cut in line. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, mistake-fix worktable (2-3)."
  },
  "b4m6-23-q3": {
    "scenarioText": "Someone says \"just kidding\" after being mean. Does that fix it. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, repair toolkit shelf (2-3)."
  },
  "b4m6-45-q1": {
    "scenarioText": "What makes an apology stronger. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, oops repair lab bench (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-45-q2": {
    "scenarioText": "You borrowed something without asking and broke it. Best repair. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, mistake-fix worktable (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-45-q3": {
    "scenarioText": "What makes repair real. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, repair toolkit shelf (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-68-q1": {
    "scenarioText": "Why is accountability different from shame. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, oops repair lab bench (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-68-q2": {
    "scenarioText": "You posted something hurtful online. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, mistake-fix worktable (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m6-68-q3": {
    "scenarioText": "A friend says \"I don't accept your apology.\". Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, repair toolkit shelf (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-23-q1": {
    "scenarioText": "A student feels nervous before a turn. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, focus flame altar (2-3)."
  },
  "b4m8-23-q2": {
    "scenarioText": "You feel frustrated during a game. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, final mission review desk (2-3)."
  },
  "b4m8-23-q3": {
    "scenarioText": "Name the feeling plus a helper move equals…. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, courage combo checklist (2-3)."
  },
  "b4m8-45-q1": {
    "scenarioText": "After calming down,. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, focus flame altar (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-45-q2": {
    "scenarioText": "After a tough conversation,. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, final mission review desk (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-45-q3": {
    "scenarioText": "Brave choice plus calm body equals…. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, courage combo checklist (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-68-q1": {
    "scenarioText": "Which full cycle shows strong self-regulation. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, focus flame altar (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-68-q2": {
    "scenarioText": "Which step comes right after \"pause\" in the regulation cycle. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, final mission review desk (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m8-68-q3": {
    "scenarioText": "Why practice the full regulation cycle. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, courage combo checklist (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-k1-q1": {
    "scenarioText": "What does Charlie check first. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, twin plant window ledge (K-1)."
  },
  "cm5-k1-q2": {
    "scenarioText": "One plant has dry soil. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, thriving-vs-wilt shelf (K-1)."
  },
  "cm5-k1-q3": {
    "scenarioText": "Charlie waters the dry plant. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, leaf-check station (K-1)."
  },
  "cm5-23-q1": {
    "scenarioText": "One plant is near the window and one is in the dark corner. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, twin plant window ledge (2-3)."
  },
  "cm5-23-q2": {
    "scenarioText": "The happy plant gets watered on schedule. The sad one was skipped twice. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, thriving-vs-wilt shelf (2-3)."
  },
  "cm5-45-q1": {
    "scenarioText": "What evidence helps Charlie explain the wilted plant. Scene: At the invention table, Charlie Perk compares two test results side by side, twin plant window ledge (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-45-q2": {
    "scenarioText": "The wilted plant's soil is dry AND it sits in shade. Scene: At the invention table, Charlie Perk compares two test results side by side, thriving-vs-wilt shelf (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-45-q3": {
    "scenarioText": "After Charlie adds water, the plant perks up a little. Scene: At the invention table, Charlie Perk compares two test results side by side, leaf-check station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm5-68-q3": {
    "scenarioText": "A classmate says the sad plant is \"just dramatic.\". Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, leaf-check station (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-k1-q1": {
    "scenarioText": "What brave step can Zeke take. Scene: In the cafeteria, Zeke pauses near a table with an open seat, talent signup sheet (K-1)."
  },
  "zkm6-k1-q2": {
    "scenarioText": "Zeke's stomach feels flip-floppy. Scene: In the cafeteria, Zeke pauses near a table with an open seat, flippy-stomach stage door (K-1)."
  },
  "zkm6-k1-q3": {
    "scenarioText": "What is one tiny brave step. Scene: In the cafeteria, Zeke pauses near a table with an open seat, tryout courage corner (K-1)."
  },
  "zkm6-45-q1": {
    "scenarioText": "Zeke feels nervous but still wants to try. Scene: At the group project table, Zeke balances his idea with the team's plan, talent signup sheet (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-45-q2": {
    "scenarioText": "Zeke's hands are shaky before signup. Scene: At the group project table, Zeke balances his idea with the team's plan, flippy-stomach stage door (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-45-q3": {
    "scenarioText": "Nervous feelings show up. Scene: At the group project table, Zeke balances his idea with the team's plan, tryout courage corner (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-68-q1": {
    "scenarioText": "What shows real courage. Scene: Before a team captain huddle, Zeke reads the room and the roster, talent signup sheet (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-68-q2": {
    "scenarioText": "Zeke wants to perform but fear says \"skip it.\". Scene: Before a team captain huddle, Zeke reads the room and the roster, flippy-stomach stage door (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm6-68-q3": {
    "scenarioText": "What is courage. Scene: Before a team captain huddle, Zeke reads the room and the roster, tryout courage corner (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-k1-q1": {
    "scenarioText": "What kind choice can Zeke make. Scene: In the cafeteria, Zeke pauses near a table with an open seat, captain clipboard huddle (K-1)."
  },
  "zkm7-k1-q2": {
    "scenarioText": "A kid is standing alone at the edge of the game. Scene: In the cafeteria, Zeke pauses near a table with an open seat, pick-last roster board (K-1)."
  },
  "zkm7-k1-q3": {
    "scenarioText": "Why include everyone. Scene: In the cafeteria, Zeke pauses near a table with an open seat, team leader mat (K-1)."
  },
  "zkm7-45-q1": {
    "scenarioText": "How can Zeke be a fair captain. Scene: At the group project table, Zeke balances his idea with the team's plan, captain clipboard huddle (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-45-q2": {
    "scenarioText": "Zeke only passes to his closest friends. Scene: At the group project table, Zeke balances his idea with the team's plan, pick-last roster board (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-45-q3": {
    "scenarioText": "A quiet teammate has a good idea. Scene: At the group project table, Zeke balances his idea with the team's plan, team leader mat (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-68-q1": {
    "scenarioText": "What is inclusive leadership. Scene: Before a team captain huddle, Zeke reads the room and the roster, captain clipboard huddle (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-68-q2": {
    "scenarioText": "Zeke wants to win but sees someone always picked last. Best leadership move. Scene: Before a team captain huddle, Zeke reads the room and the roster, pick-last roster board (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "zkm7-68-q3": {
    "scenarioText": "What is belonging on a team. Scene: Before a team captain huddle, Zeke reads the room and the roster, team leader mat (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-23-q1": {
    "scenarioText": "A student feels upset and wants to yell. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, calm-down countdown timer (2-3)."
  },
  "b4m5-23-q2": {
    "scenarioText": "Your hands are in tight fists. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, big-feeling alert bell (2-3)."
  },
  "b4m5-23-q3": {
    "scenarioText": "A friend is upset. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, cool-down practice mat (2-3)."
  },
  "b4m5-45-q1": {
    "scenarioText": "Why is it helpful to pause before responding. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, calm-down countdown timer (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-45-q2": {
    "scenarioText": "A text message makes you angry. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, big-feeling alert bell (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-45-q3": {
    "scenarioText": "What does \"pause\" mean in a calm-down. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, cool-down practice mat (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-68-q2": {
    "scenarioText": "A group project conflict starts while everyone is stressed. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, big-feeling alert bell (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-68-q3": {
    "scenarioText": "Why regulate before discussing a problem. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, cool-down practice mat (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-23-q1": {
    "scenarioText": "A student makes a mistake while reading. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, confidence charger dock (2-3)."
  },
  "b4m7-23-q2": {
    "scenarioText": "A math problem feels tricky. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, effort-notice station (2-3)."
  },
  "b4m7-23-q3": {
    "scenarioText": "Someone says \"You can't do it.\". Scene: During camp check-in, B-4's mood scanner hums near the activity mats, try-again boost panel (2-3)."
  },
  "b4m7-45-q1": {
    "scenarioText": "How can a student build confidence after struggling. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, confidence charger dock (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-45-q2": {
    "scenarioText": "You failed the first attempt at a presentation. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, effort-notice station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-45-q3": {
    "scenarioText": "Comparing yourself to everyone hurts confidence. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, try-again boost panel (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-68-q2": {
    "scenarioText": "Thought: \"Everyone else gets this except me.\". Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, effort-notice station (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-68-q3": {
    "scenarioText": "How does effort relate to confidence. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, try-again boost panel (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-23-q2": {
    "scenarioText": "Charlie finds big footprints AND small footprints. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, lettuce mystery bed (2-3)."
  },
  "cm2-23-q2": {
    "scenarioText": "Charlie predicts the peeled orange will sink. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, peel-and-drop station (2-3)."
  },
  "cm3-23-q3": {
    "scenarioText": "Charlie writes down each time he hears the squeak. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, mystery sound map (2-3)."
  },
  "cm4-23-q2": {
    "scenarioText": "Charlie adds a little more vinegar and gets more bubbles. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, tiny-eruption table (2-3)."
  },
  "cm5-23-q3": {
    "scenarioText": "Charlie moves the sad plant closer to the window for one week. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, leaf-check station (2-3)."
  },
  "cm6-23-q2": {
    "scenarioText": "Charlie swaps the left and right wheel cables. The robot still spins. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, spin-fix workbench (2-3)."
  },
  "cm6-23-q3": {
    "scenarioText": "Charlie writes down each fix he tries. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, tiny-driver track (2-3)."
  },
  "cm7-23-q2": {
    "scenarioText": "Charlie suggests a wider base. His teammate adds diagonal sticks. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, leaning-build table (2-3)."
  },
  "cm7-k1-q2": {
    "scenarioText": "One teammate holds the base while another adds sticks. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, leaning-build table (K-1)."
  },
  "cm7-k1-q3": {
    "scenarioText": "The tower leans a little. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, stick-and-puff station (K-1)."
  },
  "cm7-23-q1": {
    "scenarioText": "What helps the team improve the tower. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, marshmallow tower mat (2-3)."
  },
  "cm7-23-q3": {
    "scenarioText": "Version 1 fell. Version 2 stood taller but wobbled. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, stick-and-puff station (2-3)."
  },
  "cm7-45-q1": {
    "scenarioText": "Why should Charlie test a small tower before making it taller. Scene: At the invention table, Charlie Perk compares two test results side by side, marshmallow tower mat (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm7-45-q2": {
    "scenarioText": "A teammate notices the middle joint is loose. Scene: At the invention table, Charlie Perk compares two test results side by side, leaning-build table (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm7-45-q3": {
    "scenarioText": "The team's tallest try fell. Their medium try stayed up. Scene: At the invention table, Charlie Perk compares two test results side by side, stick-and-puff station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm7-68-q3": {
    "scenarioText": "One teammate wants height, another wants stability. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, stick-and-puff station (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "dv-q1": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 1 — What is the most helpful first thought."
  },
  "dv-q2": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 2 — What is the best response."
  },
  "dv-q3": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 3 — What should an adult focus on first."
  },
  "dv-q4": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 4 — What might be happening."
  },
  "dv-q5": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 5 — What is a supportive response."
  },
  "dv-q6": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 6 — What should an adult consider."
  },
  "dv-q7": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 7 — What helps most."
  },
  "dv-q8": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 8 — What mindset should adults adopt.",
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "b4m3-23-q1": {
    "scenarioText": "You do not understand the directions. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, brave choice console (2-3)."
  },
  "b4m3-23-q2": {
    "scenarioText": "You feel nervous about trying a new activity. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, helpful-choice practice pad (2-3)."
  },
  "b4m3-23-q3": {
    "scenarioText": "You see a classmate struggling with a task. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, courage button bay (2-3)."
  },
  "b4m3-45-q2": {
    "scenarioText": "A hard assignment makes a student want to avoid it completely. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, helpful-choice practice pad (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m3-68-q1": {
    "scenarioText": "A group is laughing at someone's mistake. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, brave choice console (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m3-68-q2": {
    "scenarioText": "Friends pressure a student to copy answers on a quiz. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, helpful-choice practice pad (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m3-68-q3": {
    "scenarioText": "After a fight, a student wants to ghost a friend instead of talking. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, courage button bay (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-k1-q2": {
    "scenarioText": "Charlie sees the footprints go toward the lettuce. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, lettuce mystery bed (K-1)."
  },
  "cm1-k1-q3": {
    "scenarioText": "Charlie finds a tiny feather near the footprints. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, snack-track sand path (K-1)."
  },
  "cm1-23-q1": {
    "scenarioText": "What clue should Charlie compare. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, garden footprint trail (2-3)."
  },
  "cm1-23-q3": {
    "scenarioText": "The footprints have three pointy marks. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, snack-track sand path (2-3)."
  },
  "cm1-45-q1": {
    "scenarioText": "Why should Charlie write down. Scene: At the invention table, Charlie Perk compares two test results side by side, garden footprint trail (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-45-q3": {
    "scenarioText": "Before guessing. Scene: At the invention table, Charlie Perk compares two test results side by side, snack-track sand path (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-68-q3": {
    "scenarioText": "A classmate says, \"Definitely the hamster!\". Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, snack-track sand path (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-k1-q1": {
    "scenarioText": "What changed in Charlie's experiment. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, floating orange tub (K-1)."
  },
  "cm2-k1-q2": {
    "scenarioText": "The whole orange floated. The peeled orange sank. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, peel-and-drop station (K-1)."
  },
  "cm2-k1-q3": {
    "scenarioText": "Charlie wants to try again. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, sink-or-float table (K-1)."
  },
  "cm2-23-q1": {
    "scenarioText": "What should Charlie do before dropping the peeled orange. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, floating orange tub (2-3)."
  },
  "cm2-23-q3": {
    "scenarioText": "The peeled orange sank again. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, sink-or-float table (2-3)."
  },
  "cm2-45-q1": {
    "scenarioText": "Why might the unpeeled orange float better. Scene: At the invention table, Charlie Perk compares two test results side by side, floating orange tub (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-45-q2": {
    "scenarioText": "When Charlie removes the peel,. Scene: At the invention table, Charlie Perk compares two test results side by side, peel-and-drop station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-k1-q2": {
    "scenarioText": "Charlie's volcano made one tiny bubble. Is that a failure. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, tiny-eruption table (K-1)."
  },
  "cm4-k1-q3": {
    "scenarioText": "Charlie wants a bigger reaction. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, bubble-test station (K-1)."
  },
  "cm4-23-q1": {
    "scenarioText": "What is the smart way to improve the volcano. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, baking soda volcano bay (2-3)."
  },
  "cm4-23-q3": {
    "scenarioText": "Why should Charlie not change vinegar AND baking soda at the same time. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, bubble-test station (2-3)."
  },
  "cm4-45-q1": {
    "scenarioText": "Why should Charlie measure the baking soda and vinegar. Scene: At the invention table, Charlie Perk compares two test results side by side, baking soda volcano bay (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-45-q2": {
    "scenarioText": "Test A: 1 spoon baking soda, small bubble. Test B: 2 spoons, bigger bubble. Scene: At the invention table, Charlie Perk compares two test results side by side, tiny-eruption table (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-68-q3": {
    "scenarioText": "Three tries with the same weak bubble. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, bubble-test station (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-23-q1": {
    "scenarioText": "A student keeps looking around the room. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, focus reset station (2-3)."
  },
  "b4m4-23-q2": {
    "scenarioText": "Noise outside the window keeps pulling a student's attention away. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, breathe-move-start panel (2-3)."
  },
  "b4m4-23-q3": {
    "scenarioText": "A student keeps thinking about recess instead of work. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, attention reset nook (2-3)."
  },
  "b4m4-45-q1": {
    "scenarioText": "A task feels too big, so the student avoids it. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, focus reset station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-45-q3": {
    "scenarioText": "A nearby screen keeps tempting a student away from homework. Scene: In the group challenge lab, B-4's feeling finder lights up on the side table, attention reset nook (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-68-q1": {
    "scenarioText": "Why does a reset routine help attention. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, focus reset station (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm1-45-q2": {
    "scenarioText": "Charlie draws the footprint shape in his notebook. Scene: At the invention table, Charlie Perk compares two test results side by side, lettuce mystery bed (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm2-45-q3": {
    "scenarioText": "Charlie tests a peeled orange and an unpeeled orange in the same bowl. Scene: At the invention table, Charlie Perk compares two test results side by side, sink-or-float table (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-45-q1": {
    "scenarioText": "Charlie hears the squeak every time the fan turns on. Scene: At the invention table, Charlie Perk compares two test results side by side, squeak hunt shelf (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm4-45-q3": {
    "scenarioText": "Charlie keeps a chart of each volcano try. Scene: At the invention table, Charlie Perk compares two test results side by side, bubble-test station (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-45-q2": {
    "scenarioText": "Charlie notices the right motor wire is unplugged. Scene: At the invention table, Charlie Perk compares two test results side by side, spin-fix workbench (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-45-q3": {
    "scenarioText": "Charlie plugs in the wire and tests again. The robot drives forward. Scene: At the invention table, Charlie Perk compares two test results side by side, tiny-driver track (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-k1-q2": {
    "scenarioText": "The squeak sounds like it comes from the back corner. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, club interruption corner (K-1)."
  },
  "cm3-k1-q3": {
    "scenarioText": "Charlie hears the squeak again. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, mystery sound map (K-1)."
  },
  "cm3-23-q1": {
    "scenarioText": "What can help Charlie solve the sound. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, squeak hunt shelf (2-3)."
  },
  "cm3-23-q2": {
    "scenarioText": "The squeak happens right after someone opens a cabinet. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, club interruption corner (2-3)."
  },
  "cm3-45-q2": {
    "scenarioText": "The squeak only happens. Scene: At the invention table, Charlie Perk compares two test results side by side, club interruption corner (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm3-45-q3": {
    "scenarioText": "A friend says the cabinet is haunted. Scene: At the invention table, Charlie Perk compares two test results side by side, mystery sound map (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-23-q1": {
    "scenarioText": "A student's shoulders are tight before reading aloud. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, body signal panel (2-3)."
  },
  "b4m2-23-q2": {
    "scenarioText": "After an unfair call in a game, a kid's jaw is clenched and fists are tight. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, heartbeat tracker wall (2-3)."
  },
  "b4m2-23-q3": {
    "scenarioText": "A student slumps their shoulders after making a mistake. Scene: During camp check-in, B-4's mood scanner hums near the activity mats, shoulder-check station (2-3)."
  },
  "b4m2-68-q1": {
    "scenarioText": "Why should someone notice body signals early. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, body signal panel (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-68-q2": {
    "scenarioText": "B-4 notices a student's voice getting louder and their face heating up. Scene: At the older learners' studio, B-4's dashboard shows a rising feeling alert, heartbeat tracker wall (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-k1-q2": {
    "scenarioText": "Charlie checks the wheels. One looks loose. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, spin-fix workbench (K-1)."
  },
  "cm6-k1-q3": {
    "scenarioText": "After fixing the wheel, the robot goes straight. Scene: In the school garden lab, Charlie Perk sets up a mini experiment tray, tiny-driver track (K-1)."
  },
  "cm6-23-q1": {
    "scenarioText": "Why should Charlie test one fix at a time. Scene: During science club, Charlie Perk spreads out notes beside a curious setup, mini robot test lane (2-3)."
  },
  "cm6-45-q1": {
    "scenarioText": "The robot turns right. Scene: At the invention table, Charlie Perk compares two test results side by side, mini robot test lane (4-5).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cm6-68-q3": {
    "scenarioText": "Two fixes did not work. One fix made the robot go straight. Scene: In the advanced science studio, Charlie Perk tracks clues from the latest trial, tiny-driver track (6-8).",
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "dv4-q7": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 7 — What should the adult do next."
  },
  "ut-q7": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 7 — What should the adult do.",
    "duplicateReviewStatus": "keep_different_context",
    "duplicateNote": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  "ut2-q7": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 7 — What should the adult say."
  },
  "ut3-q7": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 7 — What should the adult name."
  },
  "ut2-q1": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 1 — What is the best coaching response.",
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "ut2-q4": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 4 — Which response builds confidence."
  },
  "ut2-q5": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 5 — What is the best coaching move."
  },
  "ut2-q8": {
    "scenarioText": "Uncle T / Dr. Victoria mentorship moment 8 — What mindset does this show."
  },
  "b4m1-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m1-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m1-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m2-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m4-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m5-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "b4m7-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq1-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq2-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq3-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq4-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq5-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-45-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq6-68-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-45-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq7-68-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-45-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq8-68-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-45-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q4": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q5": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q6": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q7": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "cq9-68-q8": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "ms-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mst-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcl-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mml-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mcc-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-45-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-45-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-45-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-68-q1": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-68-q2": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "mdn-68-q3": {
    "whyPrompt": "Why did you choose this answer? Use one detail from the scenario."
  },
  "dv3-q8": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "dv3-q3": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "dv3-q7": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "dv3-q4": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "dv3-q6": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "dv4-q4": {
    "duplicateReviewStatus": "keep_different_context",
    "duplicateNote": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  "ut-q5": {
    "duplicateReviewStatus": "keep_different_context",
    "duplicateNote": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  "dv5-q6": {
    "duplicateReviewStatus": "keep_different_context",
    "duplicateNote": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  "ut2-q2": {
    "duplicateReviewStatus": "keep_different_context",
    "duplicateNote": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  "ut-q1": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "ut2-q3": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  "ut3-q5": {
    "duplicateReviewStatus": "needs_review_duplicate",
    "duplicateNote": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  }
};
