import type { ProductionDuplicateRegistryEntry } from './productionQualityTypes';

/** Generated by scripts/question-audit/buildProductionQualityManifest.ts */
export const PRODUCTION_DUPLICATE_REGISTRY: ProductionDuplicateRegistryEntry[] = [
  {
    "groupKey": "what mindset should adults adopt",
    "questionIds": [
      "dv-q8",
      "dv3-q8"
    ],
    "action": "needs_review_duplicate",
    "note": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  {
    "groupKey": "what may help",
    "questionIds": [
      "dv3-q3",
      "dv3-q7"
    ],
    "action": "needs_review_duplicate",
    "note": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  {
    "groupKey": "what support helps",
    "questionIds": [
      "dv3-q4",
      "dv3-q6"
    ],
    "action": "needs_review_duplicate",
    "note": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  {
    "groupKey": "what should the adult avoid",
    "questionIds": [
      "dv4-q4",
      "ut-q5"
    ],
    "action": "keep_different_context",
    "note": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  {
    "groupKey": "what should the adult do",
    "questionIds": [
      "dv5-q6",
      "ut-q7",
      "ut2-q2"
    ],
    "action": "keep_different_context",
    "note": "Keep both copies — used across victoria/uncle-t or adult contexts."
  },
  {
    "groupKey": "what is the best coaching response",
    "questionIds": [
      "ut-q1",
      "ut2-q1"
    ],
    "action": "needs_review_duplicate",
    "note": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  },
  {
    "groupKey": "what should the adult notice",
    "questionIds": [
      "ut2-q3",
      "ut3-q5"
    ],
    "action": "needs_review_duplicate",
    "note": "Exact duplicate in same mission context — mark for human merge review; overlay kept both IDs."
  }
];
