import type { GradeBand } from '../question-audit/types';

export const CHARLIE_STEMS: Record<GradeBand, string[]> = {
  'K-1': [
    'What should Charlie observe next as a scientist?',
    'Which change should Charlie try first?',
    'What might Charlie notice in the test?',
    'Which step helps Charlie learn from the test?',
    'What should Charlie check before guessing?',
    'Which try teaches Charlie the most?',
    'What should Charlie watch for next?',
    'Which test step comes first for Charlie?',
  ],
  '2-3': [
    'Which test would give the strongest evidence?',
    'Which variable should Charlie change first?',
    'Which result best supports the idea?',
    'What should Charlie observe before deciding?',
    'Which fair test helps Charlie compare results?',
    'Which prediction fits the evidence so far?',
    'Which change would teach Charlie the most?',
    'Which observation best answers the question?',
    'Which step keeps the test fair?',
    'Which outcome best matches the hypothesis?',
  ],
  '4-5': [
    'Which test would give the strongest evidence?',
    'Which variable should Charlie change first?',
    'Which result best supports the idea?',
    'Which fair test would compare the outcomes best?',
    'Which observation best supports the prediction?',
    'Which evidence best explains the result?',
    'Which change should Charlie measure next?',
    'Which trial would give the clearest comparison?',
    'Which variable matters most in this experiment?',
    'Which conclusion fits the repeated trials?',
    'Which step should Charlie take before concluding?',
    'Which test design controls the other variables?',
  ],
  '6-8': [
    'Which test would give the strongest evidence?',
    'Which variable should Charlie change first?',
    'Which result best supports the idea?',
    'Which fair test would isolate the variable?',
    'Which evidence best supports the hypothesis?',
    'Which observation best explains the pattern?',
    'Which trial design controls extraneous variables?',
    'Which measurement would strengthen the conclusion?',
    'Which change produces the most reliable comparison?',
    'Which result best rules out the alternate idea?',
    'Which step should Charlie repeat before concluding?',
    'Which variable should stay constant in the fair test?',
  ],
};

export const ZEKE_STEMS: Record<GradeBand, string[]> = {
  'K-1': [
    'Which kind words help the team first?',
    'Which choice helps everyone feel included?',
    'What should Zeke try first with friends?',
    'Which move helps the group work together?',
    'Which response shows Zeke is listening?',
    'Which step helps the team feel ready?',
    'Which choice shares time fairly?',
    'Which idea helps a friend join in?',
  ],
  '2-3': [
    'Which leadership choice helps everyone contribute?',
    'Which plan builds trust across the team?',
    'Which response balances courage and teamwork?',
    'Which move helps the group solve the problem?',
    'Which choice includes a quiet teammate?',
    'Which step helps the team listen first?',
    'Which response keeps the group working together?',
    'Which plan helps two ideas fit together?',
    'Which choice shows fair leadership?',
    'Which move helps the team recover together?',
  ],
  '4-5': [
    'Which leadership choice helps everyone contribute?',
    'Which plan builds trust across the team?',
    'Which response balances courage and teamwork?',
    'Which tradeoff helps the whole group most?',
    'Which move includes a teammate who feels left out?',
    'Which plan compares two fair ways to decide?',
    'Which response keeps the team communicating?',
    'Which leadership step helps without ignoring anyone?',
    'Which choice builds trust during a conflict?',
    'Which plan turns competition into collaboration?',
    'Which response models calm leadership?',
    'Which move helps the group reach a fair decision?',
  ],
  '6-8': [
    'Which leadership choice helps everyone contribute?',
    'Which plan builds trust across the team?',
    'Which response balances courage and teamwork?',
    'Which tradeoff best serves the whole group?',
    'Which leadership plan compares both sides fairly?',
    'Which move helps the team repair trust?',
    'Which response shows courage without shutting others out?',
    'Which plan helps every voice get heard?',
    'Which choice balances speed with inclusion?',
    'Which leadership step matches the team values?',
    'Which response turns tension into collaboration?',
    'Which plan compares courage with group needs?',
  ],
};

export const B4_STEMS: Record<GradeBand, string[]> = {
  'K-1': [
    'Which feeling should B-4 notice first?',
    'What feeling might B-4 name from these clues?',
    'Which body signal should B-4 check first?',
    'Which feeling fits what happened?',
    'What feeling might be getting bigger?',
    'Which clue helps B-4 name the feeling?',
    'Which feeling matches the body signals?',
    'What might B-4 name from these signs?',
  ],
  '2-3': [
    'Which feeling should B-4 notice first?',
    'Which strategy fits the body signal?',
    'Which response keeps the flame steady?',
    'Which coping step fits after naming the feeling?',
    'Which calm choice fits this moment?',
    'Which regulation step fits the body clues?',
    'Which feeling name fits the situation best?',
    'Which strategy compares two calm choices?',
    'Which response helps B-4 stay steady?',
    'Which coping plan fits after the feeling is named?',
  ],
  '4-5': [
    'Which feeling should B-4 notice first?',
    'Which strategy fits the body signal?',
    'Which response keeps the flame steady?',
    'Which coping step fits best after naming the feeling?',
    'Which two strategies compare well for this moment?',
    'Which regulation choice fits the trigger best?',
    'Which calm-down step fits before acting?',
    'Which feeling detail best matches the clues?',
    'Which coping strategy fits the body signals?',
    'Which regulation step compares two helpful choices?',
    'Which response helps B-4 regulate before deciding?',
    'Which strategy fits after B-4 names the feeling?',
  ],
  '6-8': [
    'Which feeling should B-4 notice first?',
    'Which strategy fits the body signal?',
    'Which response keeps the flame steady?',
    'Which regulation step fits before discussing the problem?',
    'Which coping strategy best compares two regulation paths?',
    'Which feeling detail best compares trigger and intensity?',
    'Which regulation sequence fits the focus reset?',
    'Which coping choice compares repair with avoidance?',
    'Which self-awareness clue matters most here?',
    'Which regulation strategy fits buzzing body signals?',
    'Which calm-down plan compares pace with pressure?',
    'Which strategy fits after naming a mixed feeling?',
  ],
};

export function pickStemTemplate(
  character: string,
  gradeBand: GradeBand,
  questionId: string,
  slot: number,
): string | null {
  const pools: Record<string, Record<GradeBand, string[]>> = {
    charlie: CHARLIE_STEMS,
    zeke: ZEKE_STEMS,
    b4: B4_STEMS,
  };
  const pool = pools[character]?.[gradeBand];
  if (!pool?.length) return null;
  const hash = questionId.split('').reduce((sum, ch) => sum + ch.charCodeAt(0), 0);
  return pool[(hash + slot) % pool.length];
}
