import React, { useEffect, useState } from 'react';
import { getProviderView } from '../../../lib/crmProviderApi';
import { isSupabaseConfigured, supabase } from '../../../lib/supabaseClient';

type Diagnostics = { configured?:boolean; serverReachable?:boolean; flags?:Record<string,boolean>; lastAttemptAt?:string|null; lastSuccessfulAt?:string|null; mostRecentError?:string|null; eventType?:string|null; internalIdentifier?:string|null; intendedTag?:string|null; maskedEmail?:string|null; recentEvents?:Array<Record<string,unknown>>; communicationDeliveries?:Array<Record<string,unknown>> };
export default function AdminKitDiagnosticsTab(){
  const [data,setData]=useState<Diagnostics|null>(null); const [message,setMessage]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=()=>void getProviderView('crm-kit-diagnostics').then((result)=>{setLoading(false);if(result.ok)setData(result.data as Diagnostics);else setMessage(result.error || 'Diagnostics unavailable.');}); useEffect(load,[]);
  const run=async()=>{if(!isSupabaseConfigured()||!supabase){setMessage('Admin session unavailable.');return;}const {data:session}=await supabase.auth.getSession();const response=await fetch('/.netlify/functions/crm-kit-diagnostics',{method:'POST',headers:{Authorization:`Bearer ${session.session?.access_token || ''}`}});const result=await response.json();setMessage(result.message || (response.ok?'Dry run complete.':'Dry run failed.'));if(response.ok)load();};
  const row=(label:string,value:unknown)=><div className="adminPortal-programRow"><span>{label}</span><strong>{value === null || value === undefined || value === '' ? 'No record yet' : String(value)}</strong></div>;
  return <div className="adminPortal-stack"><section className="adminPortal-card"><h2 className="adminPortal-cardTitle">Kit Integration Diagnostics</h2><p className="adminPortal-cardSub">Protected server-side status. Secrets are never returned, and the test is a no-write dry run.</p>{message?<p role="status" className="adminPortal-warning">{message}</p>:null}{loading?<p>Loading diagnostics…</p>:<div className="adminPortal-programList">{row('Required environment configured',data?.configured?'Yes':'No')}{row('Server integration reachable',data?.serverReachable?'Yes':'No')}{row('Last synchronization attempt',data?.lastAttemptAt)}{row('Last successful synchronization',data?.lastSuccessfulAt)}{row('Most recent error',data?.mostRecentError)}{row('Triggering event',data?.eventType)}{row('Internal identifier',data?.internalIdentifier)}{row('Intended Kit tag / segment',data?.intendedTag)}{row('Email',data?.maskedEmail)}</div>}<button type="button" className="adminPortal-btn adminPortal-btn--primary" onClick={()=>void run()}>Run Test Sync</button><p className="adminPortal-sectionHelper">This validates authorization and configuration only. It never creates a subscriber or contacts Kit.</p></section><section className="adminPortal-card"><h2 className="adminPortal-cardTitle">Recent Sync Events</h2><pre className="adminPortal-codeBlock">{JSON.stringify(data?.recentEvents || [],null,2)}</pre></section><section className="adminPortal-card"><h2 className="adminPortal-cardTitle">Weekly Summary Delivery Log</h2><p className="adminPortal-cardSub">Prepared records only. Provider delivery remains disabled.</p><pre className="adminPortal-codeBlock">{JSON.stringify(data?.communicationDeliveries || [],null,2)}</pre></section></div>;
}
