import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { fetchAdminQuestionSets, postAdminQuestionAction } from '../../../lib/learningContentApi';
import { exportQuestionSetsCsv, parseQuestionImport } from '../../../lib/questionImport';

type Question = { id:string; prompt:string; category:string; active:boolean; display_order:number; answer_options?:unknown[]; correct_answer?:unknown; explanation?:string|null };
type SetRow = { id:string; title:string; grade_band:string; month_number:number; week_number:number; module_key:string; skill:string; status:string; version:number; learning_questions?:Question[] };

function QuestionEditor({ question, onSave }: { question:Question; onSave:(values:Record<string,unknown>)=>void }) {
  const [prompt,setPrompt]=useState(question.prompt); const [options,setOptions]=useState(JSON.stringify(question.answer_options || [])); const [answer,setAnswer]=useState(JSON.stringify(question.correct_answer ?? null)); const [explanation,setExplanation]=useState(question.explanation || '');
  return <div className="adminPortal-questionEditor"><label>Prompt<textarea value={prompt} onChange={(event)=>setPrompt(event.target.value)} /></label><label>Answer options (JSON)<textarea value={options} onChange={(event)=>setOptions(event.target.value)} /></label><label>Correct answer (JSON)<textarea value={answer} onChange={(event)=>setAnswer(event.target.value)} /></label><label>Explanation<textarea value={explanation} onChange={(event)=>setExplanation(event.target.value)} /></label><button type="button" className="adminPortal-btn adminPortal-btn--primary" onClick={()=>{try{onSave({prompt,answer_options:JSON.parse(options),correct_answer:JSON.parse(answer),explanation});}catch{onSave({prompt,explanation});}}}>Save question</button></div>;
}

export default function AdminQuestionBankTab() {
  const [items,setItems]=useState<SetRow[]>([]); const [filters,setFilters]=useState({gradeBand:'',status:'',month:'',week:''}); const [message,setMessage]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [importText,setImportText]=useState(''); const [validated,setValidated]=useState<ReturnType<typeof parseQuestionImport>|null>(null); const [newSet,setNewSet]=useState({title:'',grade_band:'3_5',week_number:'1',skill:''});
  const load=useCallback(async()=>{setLoading(true);const result=await fetchAdminQuestionSets(filters);setItems(result.items as SetRow[]);setMessage(result.error||null);setLoading(false);},[filters]);
  useEffect(()=>{void load();},[load]);
  const exportJson=useMemo(()=>JSON.stringify(items.map((item)=>({...item,questions:item.learning_questions,learning_questions:undefined})),null,2),[items]); const exportCsv=useMemo(()=>exportQuestionSetsCsv(items),[items]);
  const act=async(payload:Record<string,unknown>)=>{const result=await postAdminQuestionAction(payload);setMessage(result.ok?'Question bank updated.':result.error||'Update failed.');if(result.ok)await load();return result;};
  const validate=async()=>{try{const parsed=parseQuestionImport(importText);const result=await postAdminQuestionAction({action:'validate_import',items:parsed});const errors=(result.data as {errors?:string[]}|undefined)?.errors||[];setValidated(errors.length?null:parsed);setMessage(errors.length?errors.join(' '):'Import is valid and ready to create new draft sets.');}catch{setValidated(null);setMessage('Import is not valid JSON or CSV.');}};
  const reorder=(set:SetRow,questionId:string,direction:-1|1)=>{const ordered=[...(set.learning_questions||[])].sort((a,b)=>a.display_order-b.display_order);const index=ordered.findIndex((question)=>question.id===questionId);const target=index+direction;if(index<0||target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];void act({action:'reorder',id:set.id,questionIds:ordered.map((question)=>question.id)});};
  return <div className="adminPortal-stack"><section className="adminPortal-card"><h2 className="adminPortal-cardTitle">Question Bank</h2><p className="adminPortal-cardSub">Editable 12-week content by grade band. Draft content is never returned to learners.</p>
    <form className="adminPortal-questionFilters" onSubmit={(event)=>{event.preventDefault();void act({action:'create_set',values:{...newSet,month_number:Math.ceil(Number(newSet.week_number)/4),module_key:`week-${newSet.week_number}`,status:'draft',version:1}});}}><label>New set title<input value={newSet.title} onChange={(event)=>setNewSet({...newSet,title:event.target.value})} required /></label><label>Grade band<select value={newSet.grade_band} onChange={(event)=>setNewSet({...newSet,grade_band:event.target.value})}><option value="k_2">K–2</option><option value="3_5">Grades 3–5</option><option value="6_8">Grades 6–8</option></select></label><label>Week<input type="number" min="1" value={newSet.week_number} onChange={(event)=>setNewSet({...newSet,week_number:event.target.value})} /></label><label>Skill<input value={newSet.skill} onChange={(event)=>setNewSet({...newSet,skill:event.target.value})} required /></label><button className="adminPortal-btn adminPortal-btn--primary" type="submit">Create draft set</button></form>
    <div className="adminPortal-questionFilters"><label>Filter grade band<select value={filters.gradeBand} onChange={(event)=>setFilters({...filters,gradeBand:event.target.value})}><option value="">All</option><option value="k_2">K–2</option><option value="3_5">Grades 3–5</option><option value="6_8">Grades 6–8</option></select></label><label>Status<select value={filters.status} onChange={(event)=>setFilters({...filters,status:event.target.value})}><option value="">All</option>{['draft','internal_review','educator_review','published','archived'].map((value)=><option key={value}>{value}</option>)}</select></label><label>Month<input type="number" min="1" value={filters.month} onChange={(event)=>setFilters({...filters,month:event.target.value})} /></label><label>Week<input type="number" min="1" value={filters.week} onChange={(event)=>setFilters({...filters,week:event.target.value})} /></label></div>
    {message?<p role="status" className={message.includes('failed')||message.includes('not valid')?'adminPortal-error':'adminPortal-success'}>{message}</p>:null}<p className="adminPortal-count">{loading?'Loading…':`${items.length} question sets`}</p><div className="adminPortal-questionSetList">{items.map((item)=><article key={item.id} className="adminPortal-questionSet"><div><h3>{item.title}</h3><p>Week {item.week_number} · {item.grade_band.replace('_','–')} · v{item.version} · {item.learning_questions?.length||0} questions</p></div><span className="adminPortal-statusPill">{item.status}</span><div className="adminPortal-toolbarActions"><button type="button" className="adminPortal-btn adminPortal-btn--ghost" onClick={()=>void act({action:'duplicate',id:item.id,gradeBand:item.grade_band})}>Duplicate</button>{item.status!=='published'?<button type="button" className="adminPortal-btn adminPortal-btn--primary" onClick={()=>void act({action:'set_status',id:item.id,status:'published'})}>Publish</button>:null}<button type="button" className="adminPortal-btn adminPortal-btn--ghost" onClick={()=>void act({action:'set_status',id:item.id,status:'archived'})}>Archive</button></div><details><summary>Edit and preview questions</summary>{[...(item.learning_questions||[])].sort((a,b)=>a.display_order-b.display_order).map((question)=><details key={question.id} className="adminPortal-questionDetail"><summary>{question.display_order}. {question.prompt}</summary><div className="adminPortal-toolbarActions"><button type="button" className="adminPortal-btn adminPortal-btn--ghost" onClick={()=>reorder(item,question.id,-1)}>Move up</button><button type="button" className="adminPortal-btn adminPortal-btn--ghost" onClick={()=>reorder(item,question.id,1)}>Move down</button><label><input type="checkbox" checked={question.active} onChange={(event)=>void act({action:'update_question',id:question.id,values:{active:event.target.checked}})} /> Active</label></div><QuestionEditor question={question} onSave={(values)=>void act({action:'update_question',id:question.id,values})} /></details>)}</details></article>)}</div>
  </section><section className="adminPortal-card"><h2 className="adminPortal-cardTitle">Import / Export</h2><p className="adminPortal-cardSub">JSON or CSV imports are validated first and create draft sets only; existing content is never overwritten.</p><textarea className="adminPortal-importArea" value={importText} onChange={(event)=>{setImportText(event.target.value);setValidated(null);}} placeholder="Paste JSON or CSV question sets to validate" /><div className="adminPortal-toolbarActions"><button className="adminPortal-btn adminPortal-btn--primary" type="button" onClick={()=>void validate()}>Validate import</button><button className="adminPortal-btn adminPortal-btn--primary" type="button" disabled={!validated} onClick={()=>validated&&void act({action:'import_json',items:validated})}>Import validated drafts</button><button className="adminPortal-btn adminPortal-btn--ghost" type="button" onClick={()=>void navigator.clipboard.writeText(exportJson)}>Copy JSON</button><button className="adminPortal-btn adminPortal-btn--ghost" type="button" onClick={()=>void navigator.clipboard.writeText(exportCsv)}>Copy CSV</button></div></section></div>;
}
