const { KIT_EVENT_MAP } = require('./kitLifecycleConfig');

function reportingPeriod(now=new Date()){const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const start=new Date(end);start.setUTCDate(start.getUTCDate()-7);return {start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)};}
function moduleWeek(value){const match=String(value||'').match(/(?:week[-_ ]?)(\d+)/i);return match?Number(match[1]):null;}
function buildWeeklySummary(input){const modules=(input.modules||[]).sort((a,b)=>String(a.completed_at).localeCompare(String(b.completed_at)));const latest=modules[modules.length-1];const prior=input.priorPercent??null;const current=latest?.percent_score??null;return {student_first_name:input.studentFirstName,program_name:input.programName,modules_started:new Set(modules.map((row)=>row.module_id)).size,modules_completed:modules.length,reading_activity:input.readingActivity||0,assessment_completed:Boolean(input.assessmentCompleted),weekly_skill:latest?.skill_area||input.weeklySkill||null,quiz_performance:current,improvement:current!==null&&prior!==null?Number(current)-Number(prior):null,badge_earned:input.badgeEarned||null,current_streak:input.currentStreak||0,weekly_discussion_prompt:input.discussionPrompt||'What helped you keep going when something felt difficult this week?',suggested_next_action:modules.length?'Celebrate the week and preview the next mission.':'Start one short mission together.',dashboard_url:input.dashboardUrl,module_week:moduleWeek(latest?.module_id)};}
async function prepareWeeklySummaries(supabase,now=new Date()){
  const period=reportingPeriod(now);const links=await supabase.from('guardian_relationships').select('participant_id,contact_id,contacts(id,first_name,do_not_enroll,communication_preferences(purpose,status))').eq('status','verified');if(links.error)throw links.error;let prepared=0,skipped=0;
  for(const link of links.data||[]){const contact=link.contacts;const consent=(contact?.communication_preferences||[]).find((item)=>item.purpose==='weekly_progress');if(!contact||contact.do_not_enroll||consent?.status!=='confirmed'){skipped+=1;continue;}const [student,modules,assessments,badges]=await Promise.all([supabase.from('participants').select('id,nickname,first_name,program_code,group_name').eq('id',link.participant_id).maybeSingle(),supabase.from('module_results').select('module_id,skill_area,percent_score,completed_at').eq('participant_id',link.participant_id).gte('completed_at',`${period.start}T00:00:00Z`).lt('completed_at',`${period.end}T00:00:00Z`),supabase.from('assessment_results_v2').select('id').eq('participant_id',link.participant_id).gte('completed_at',`${period.start}T00:00:00Z`).lt('completed_at',`${period.end}T00:00:00Z`).limit(1),supabase.from('player_badges').select('badge_name,earned_at').eq('participant_id',link.participant_id).gte('earned_at',`${period.start}T00:00:00Z`).lt('earned_at',`${period.end}T00:00:00Z`).order('earned_at',{ascending:false}).limit(1)]);if(!student.data){skipped+=1;continue;}const summary=buildWeeklySummary({studentFirstName:student.data.first_name||student.data.nickname||'Your learner',programName:student.data.group_name||student.data.program_code,modules:modules.data||[],assessmentCompleted:Boolean(assessments.data?.length),badgeEarned:badges.data?.[0]?.badge_name||null,dashboardUrl:process.env.PUBLIC_SITE_URL?`${process.env.PUBLIC_SITE_URL}/family-hub`:'/family-hub'});const dedupeKey=`weekly_progress_summary:${period.start}:${period.end}:${contact.id}:${link.participant_id}`;const result=await supabase.from('learning_communication_deliveries').upsert({dedupe_key:dedupeKey,provider:'kit',communication_type:'weekly_progress_summary',reporting_period_start:period.start,reporting_period_end:period.end,recipient_contact_id:contact.id,student_id:link.participant_id,status:'prepared',summary_payload:summary,updated_at:new Date().toISOString()},{onConflict:'dedupe_key'});if(result.error)skipped+=1;else prepared+=1;}
  return {period,prepared,skipped,intendedTag:KIT_EVENT_MAP.weekly_summary_ready.tag,providerQueued:false};
}
module.exports={buildWeeklySummary,moduleWeek,prepareWeeklySummaries,reportingPeriod};
